// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// <auto-generated />
#nullable enable

using System.Collections;
using System.CodeDom.Compiler;

namespace Microsoft.AspNetCore.Http;

[GeneratedCode("TextTemplatingFileGenerator", "")]
public sealed class EndpointFilterInvocationContext<T0> : EndpointFilterInvocationContext
{
    public EndpointFilterInvocationContext(HttpContext httpContext, T0 arg0)
    {
        HttpContext = httpContext;
        Arg0 = arg0;
    }

    public object? this[int index]
    {
        get => index switch
        {
            0 => Arg0,
            _ => new IndexOutOfRangeException()
        };
        set
        {
            switch (index)
            {
               case 0:
                    Arg0 = (T0)(object?)value!;
                    break;
                default:
                    break;
            }
        }
    }

    /// <inheritdoc />
    public override HttpContext HttpContext { get; }

    /// <inheritdoc />
    public override IList<object?> Arguments => new List<object?>() { Arg0, };

    internal T0 Arg0 { get; set; }
    
    /// <inheritdoc />
    public override T GetArgument<T>(int index)
    {
        return index switch
        {
           0 => (T)(object)Arg0!,
           _ => throw new IndexOutOfRangeException()
        };
    }
}
[GeneratedCode("TextTemplatingFileGenerator", "")]
public sealed class EndpointFilterInvocationContext<T0, T1> : EndpointFilterInvocationContext
{
    public EndpointFilterInvocationContext(HttpContext httpContext, T0 arg0, T1 arg1)
    {
        HttpContext = httpContext;
        Arg0 = arg0;
        Arg1 = arg1;
    }

    public object? this[int index]
    {
        get => index switch
        {
            0 => Arg0,
            1 => Arg1,
            _ => new IndexOutOfRangeException()
        };
        set
        {
            switch (index)
            {
               case 0:
                    Arg0 = (T0)(object?)value!;
                    break;
               case 1:
                    Arg1 = (T1)(object?)value!;
                    break;
                default:
                    break;
            }
        }
    }

    /// <inheritdoc />
    public override HttpContext HttpContext { get; }

    /// <inheritdoc />
    public override IList<object?> Arguments => new List<object?>() { Arg0, Arg1, };

    internal T0 Arg0 { get; set; }
    internal T1 Arg1 { get; set; }
    
    /// <inheritdoc />
    public override T GetArgument<T>(int index)
    {
        return index switch
        {
           0 => (T)(object)Arg0!,
           1 => (T)(object)Arg1!,
           _ => throw new IndexOutOfRangeException()
        };
    }
}
[GeneratedCode("TextTemplatingFileGenerator", "")]
public sealed class EndpointFilterInvocationContext<T0, T1, T2> : EndpointFilterInvocationContext
{
    public EndpointFilterInvocationContext(HttpContext httpContext, T0 arg0, T1 arg1, T2 arg2)
    {
        HttpContext = httpContext;
        Arg0 = arg0;
        Arg1 = arg1;
        Arg2 = arg2;
    }

    public object? this[int index]
    {
        get => index switch
        {
            0 => Arg0,
            1 => Arg1,
            2 => Arg2,
            _ => new IndexOutOfRangeException()
        };
        set
        {
            switch (index)
            {
               case 0:
                    Arg0 = (T0)(object?)value!;
                    break;
               case 1:
                    Arg1 = (T1)(object?)value!;
                    break;
               case 2:
                    Arg2 = (T2)(object?)value!;
                    break;
                default:
                    break;
            }
        }
    }

    /// <inheritdoc />
    public override HttpContext HttpContext { get; }

    /// <inheritdoc />
    public override IList<object?> Arguments => new List<object?>() { Arg0, Arg1, Arg2, };

    internal T0 Arg0 { get; set; }
    internal T1 Arg1 { get; set; }
    internal T2 Arg2 { get; set; }
    
    /// <inheritdoc />
    public override T GetArgument<T>(int index)
    {
        return index switch
        {
           0 => (T)(object)Arg0!,
           1 => (T)(object)Arg1!,
           2 => (T)(object)Arg2!,
           _ => throw new IndexOutOfRangeException()
        };
    }
}
[GeneratedCode("TextTemplatingFileGenerator", "")]
public sealed class EndpointFilterInvocationContext<T0, T1, T2, T3> : EndpointFilterInvocationContext
{
    public EndpointFilterInvocationContext(HttpContext httpContext, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
    {
        HttpContext = httpContext;
        Arg0 = arg0;
        Arg1 = arg1;
        Arg2 = arg2;
        Arg3 = arg3;
    }

    public object? this[int index]
    {
        get => index switch
        {
            0 => Arg0,
            1 => Arg1,
            2 => Arg2,
            3 => Arg3,
            _ => new IndexOutOfRangeException()
        };
        set
        {
            switch (index)
            {
               case 0:
                    Arg0 = (T0)(object?)value!;
                    break;
               case 1:
                    Arg1 = (T1)(object?)value!;
                    break;
               case 2:
                    Arg2 = (T2)(object?)value!;
                    break;
               case 3:
                    Arg3 = (T3)(object?)value!;
                    break;
                default:
                    break;
            }
        }
    }

    /// <inheritdoc />
    public override HttpContext HttpContext { get; }

    /// <inheritdoc />
    public override IList<object?> Arguments => new List<object?>() { Arg0, Arg1, Arg2, Arg3, };

    internal T0 Arg0 { get; set; }
    internal T1 Arg1 { get; set; }
    internal T2 Arg2 { get; set; }
    internal T3 Arg3 { get; set; }
    
    /// <inheritdoc />
    public override T GetArgument<T>(int index)
    {
        return index switch
        {
           0 => (T)(object)Arg0!,
           1 => (T)(object)Arg1!,
           2 => (T)(object)Arg2!,
           3 => (T)(object)Arg3!,
           _ => throw new IndexOutOfRangeException()
        };
    }
}
[GeneratedCode("TextTemplatingFileGenerator", "")]
public sealed class EndpointFilterInvocationContext<T0, T1, T2, T3, T4> : EndpointFilterInvocationContext
{
    public EndpointFilterInvocationContext(HttpContext httpContext, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
    {
        HttpContext = httpContext;
        Arg0 = arg0;
        Arg1 = arg1;
        Arg2 = arg2;
        Arg3 = arg3;
        Arg4 = arg4;
    }

    public object? this[int index]
    {
        get => index switch
        {
            0 => Arg0,
            1 => Arg1,
            2 => Arg2,
            3 => Arg3,
            4 => Arg4,
            _ => new IndexOutOfRangeException()
        };
        set
        {
            switch (index)
            {
               case 0:
                    Arg0 = (T0)(object?)value!;
                    break;
               case 1:
                    Arg1 = (T1)(object?)value!;
                    break;
               case 2:
                    Arg2 = (T2)(object?)value!;
                    break;
               case 3:
                    Arg3 = (T3)(object?)value!;
                    break;
               case 4:
                    Arg4 = (T4)(object?)value!;
                    break;
                default:
                    break;
            }
        }
    }

    /// <inheritdoc />
    public override HttpContext HttpContext { get; }

    /// <inheritdoc />
    public override IList<object?> Arguments => new List<object?>() { Arg0, Arg1, Arg2, Arg3, Arg4, };

    internal T0 Arg0 { get; set; }
    internal T1 Arg1 { get; set; }
    internal T2 Arg2 { get; set; }
    internal T3 Arg3 { get; set; }
    internal T4 Arg4 { get; set; }
    
    /// <inheritdoc />
    public override T GetArgument<T>(int index)
    {
        return index switch
        {
           0 => (T)(object)Arg0!,
           1 => (T)(object)Arg1!,
           2 => (T)(object)Arg2!,
           3 => (T)(object)Arg3!,
           4 => (T)(object)Arg4!,
           _ => throw new IndexOutOfRangeException()
        };
    }
}
[GeneratedCode("TextTemplatingFileGenerator", "")]
public sealed class EndpointFilterInvocationContext<T0, T1, T2, T3, T4, T5> : EndpointFilterInvocationContext
{
    public EndpointFilterInvocationContext(HttpContext httpContext, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
    {
        HttpContext = httpContext;
        Arg0 = arg0;
        Arg1 = arg1;
        Arg2 = arg2;
        Arg3 = arg3;
        Arg4 = arg4;
        Arg5 = arg5;
    }

    public object? this[int index]
    {
        get => index switch
        {
            0 => Arg0,
            1 => Arg1,
            2 => Arg2,
            3 => Arg3,
            4 => Arg4,
            5 => Arg5,
            _ => new IndexOutOfRangeException()
        };
        set
        {
            switch (index)
            {
               case 0:
                    Arg0 = (T0)(object?)value!;
                    break;
               case 1:
                    Arg1 = (T1)(object?)value!;
                    break;
               case 2:
                    Arg2 = (T2)(object?)value!;
                    break;
               case 3:
                    Arg3 = (T3)(object?)value!;
                    break;
               case 4:
                    Arg4 = (T4)(object?)value!;
                    break;
               case 5:
                    Arg5 = (T5)(object?)value!;
                    break;
                default:
                    break;
            }
        }
    }

    /// <inheritdoc />
    public override HttpContext HttpContext { get; }

    /// <inheritdoc />
    public override IList<object?> Arguments => new List<object?>() { Arg0, Arg1, Arg2, Arg3, Arg4, Arg5, };

    internal T0 Arg0 { get; set; }
    internal T1 Arg1 { get; set; }
    internal T2 Arg2 { get; set; }
    internal T3 Arg3 { get; set; }
    internal T4 Arg4 { get; set; }
    internal T5 Arg5 { get; set; }
    
    /// <inheritdoc />
    public override T GetArgument<T>(int index)
    {
        return index switch
        {
           0 => (T)(object)Arg0!,
           1 => (T)(object)Arg1!,
           2 => (T)(object)Arg2!,
           3 => (T)(object)Arg3!,
           4 => (T)(object)Arg4!,
           5 => (T)(object)Arg5!,
           _ => throw new IndexOutOfRangeException()
        };
    }
}
[GeneratedCode("TextTemplatingFileGenerator", "")]
public sealed class EndpointFilterInvocationContext<T0, T1, T2, T3, T4, T5, T6> : EndpointFilterInvocationContext
{
    public EndpointFilterInvocationContext(HttpContext httpContext, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
    {
        HttpContext = httpContext;
        Arg0 = arg0;
        Arg1 = arg1;
        Arg2 = arg2;
        Arg3 = arg3;
        Arg4 = arg4;
        Arg5 = arg5;
        Arg6 = arg6;
    }

    public object? this[int index]
    {
        get => index switch
        {
            0 => Arg0,
            1 => Arg1,
            2 => Arg2,
            3 => Arg3,
            4 => Arg4,
            5 => Arg5,
            6 => Arg6,
            _ => new IndexOutOfRangeException()
        };
        set
        {
            switch (index)
            {
               case 0:
                    Arg0 = (T0)(object?)value!;
                    break;
               case 1:
                    Arg1 = (T1)(object?)value!;
                    break;
               case 2:
                    Arg2 = (T2)(object?)value!;
                    break;
               case 3:
                    Arg3 = (T3)(object?)value!;
                    break;
               case 4:
                    Arg4 = (T4)(object?)value!;
                    break;
               case 5:
                    Arg5 = (T5)(object?)value!;
                    break;
               case 6:
                    Arg6 = (T6)(object?)value!;
                    break;
                default:
                    break;
            }
        }
    }

    /// <inheritdoc />
    public override HttpContext HttpContext { get; }

    /// <inheritdoc />
    public override IList<object?> Arguments => new List<object?>() { Arg0, Arg1, Arg2, Arg3, Arg4, Arg5, Arg6, };

    internal T0 Arg0 { get; set; }
    internal T1 Arg1 { get; set; }
    internal T2 Arg2 { get; set; }
    internal T3 Arg3 { get; set; }
    internal T4 Arg4 { get; set; }
    internal T5 Arg5 { get; set; }
    internal T6 Arg6 { get; set; }
    
    /// <inheritdoc />
    public override T GetArgument<T>(int index)
    {
        return index switch
        {
           0 => (T)(object)Arg0!,
           1 => (T)(object)Arg1!,
           2 => (T)(object)Arg2!,
           3 => (T)(object)Arg3!,
           4 => (T)(object)Arg4!,
           5 => (T)(object)Arg5!,
           6 => (T)(object)Arg6!,
           _ => throw new IndexOutOfRangeException()
        };
    }
}
[GeneratedCode("TextTemplatingFileGenerator", "")]
public sealed class EndpointFilterInvocationContext<T0, T1, T2, T3, T4, T5, T6, T7> : EndpointFilterInvocationContext
{
    public EndpointFilterInvocationContext(HttpContext httpContext, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
    {
        HttpContext = httpContext;
        Arg0 = arg0;
        Arg1 = arg1;
        Arg2 = arg2;
        Arg3 = arg3;
        Arg4 = arg4;
        Arg5 = arg5;
        Arg6 = arg6;
        Arg7 = arg7;
    }

    public object? this[int index]
    {
        get => index switch
        {
            0 => Arg0,
            1 => Arg1,
            2 => Arg2,
            3 => Arg3,
            4 => Arg4,
            5 => Arg5,
            6 => Arg6,
            7 => Arg7,
            _ => new IndexOutOfRangeException()
        };
        set
        {
            switch (index)
            {
               case 0:
                    Arg0 = (T0)(object?)value!;
                    break;
               case 1:
                    Arg1 = (T1)(object?)value!;
                    break;
               case 2:
                    Arg2 = (T2)(object?)value!;
                    break;
               case 3:
                    Arg3 = (T3)(object?)value!;
                    break;
               case 4:
                    Arg4 = (T4)(object?)value!;
                    break;
               case 5:
                    Arg5 = (T5)(object?)value!;
                    break;
               case 6:
                    Arg6 = (T6)(object?)value!;
                    break;
               case 7:
                    Arg7 = (T7)(object?)value!;
                    break;
                default:
                    break;
            }
        }
    }

    /// <inheritdoc />
    public override HttpContext HttpContext { get; }

    /// <inheritdoc />
    public override IList<object?> Arguments => new List<object?>() { Arg0, Arg1, Arg2, Arg3, Arg4, Arg5, Arg6, Arg7, };

    internal T0 Arg0 { get; set; }
    internal T1 Arg1 { get; set; }
    internal T2 Arg2 { get; set; }
    internal T3 Arg3 { get; set; }
    internal T4 Arg4 { get; set; }
    internal T5 Arg5 { get; set; }
    internal T6 Arg6 { get; set; }
    internal T7 Arg7 { get; set; }
    
    /// <inheritdoc />
    public override T GetArgument<T>(int index)
    {
        return index switch
        {
           0 => (T)(object)Arg0!,
           1 => (T)(object)Arg1!,
           2 => (T)(object)Arg2!,
           3 => (T)(object)Arg3!,
           4 => (T)(object)Arg4!,
           5 => (T)(object)Arg5!,
           6 => (T)(object)Arg6!,
           7 => (T)(object)Arg7!,
           _ => throw new IndexOutOfRangeException()
        };
    }
}
[GeneratedCode("TextTemplatingFileGenerator", "")]
public sealed class EndpointFilterInvocationContext<T0, T1, T2, T3, T4, T5, T6, T7, T8> : EndpointFilterInvocationContext
{
    public EndpointFilterInvocationContext(HttpContext httpContext, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
    {
        HttpContext = httpContext;
        Arg0 = arg0;
        Arg1 = arg1;
        Arg2 = arg2;
        Arg3 = arg3;
        Arg4 = arg4;
        Arg5 = arg5;
        Arg6 = arg6;
        Arg7 = arg7;
        Arg8 = arg8;
    }

    public object? this[int index]
    {
        get => index switch
        {
            0 => Arg0,
            1 => Arg1,
            2 => Arg2,
            3 => Arg3,
            4 => Arg4,
            5 => Arg5,
            6 => Arg6,
            7 => Arg7,
            8 => Arg8,
            _ => new IndexOutOfRangeException()
        };
        set
        {
            switch (index)
            {
               case 0:
                    Arg0 = (T0)(object?)value!;
                    break;
               case 1:
                    Arg1 = (T1)(object?)value!;
                    break;
               case 2:
                    Arg2 = (T2)(object?)value!;
                    break;
               case 3:
                    Arg3 = (T3)(object?)value!;
                    break;
               case 4:
                    Arg4 = (T4)(object?)value!;
                    break;
               case 5:
                    Arg5 = (T5)(object?)value!;
                    break;
               case 6:
                    Arg6 = (T6)(object?)value!;
                    break;
               case 7:
                    Arg7 = (T7)(object?)value!;
                    break;
               case 8:
                    Arg8 = (T8)(object?)value!;
                    break;
                default:
                    break;
            }
        }
    }

    /// <inheritdoc />
    public override HttpContext HttpContext { get; }

    /// <inheritdoc />
    public override IList<object?> Arguments => new List<object?>() { Arg0, Arg1, Arg2, Arg3, Arg4, Arg5, Arg6, Arg7, Arg8, };

    internal T0 Arg0 { get; set; }
    internal T1 Arg1 { get; set; }
    internal T2 Arg2 { get; set; }
    internal T3 Arg3 { get; set; }
    internal T4 Arg4 { get; set; }
    internal T5 Arg5 { get; set; }
    internal T6 Arg6 { get; set; }
    internal T7 Arg7 { get; set; }
    internal T8 Arg8 { get; set; }
    
    /// <inheritdoc />
    public override T GetArgument<T>(int index)
    {
        return index switch
        {
           0 => (T)(object)Arg0!,
           1 => (T)(object)Arg1!,
           2 => (T)(object)Arg2!,
           3 => (T)(object)Arg3!,
           4 => (T)(object)Arg4!,
           5 => (T)(object)Arg5!,
           6 => (T)(object)Arg6!,
           7 => (T)(object)Arg7!,
           8 => (T)(object)Arg8!,
           _ => throw new IndexOutOfRangeException()
        };
    }
}
[GeneratedCode("TextTemplatingFileGenerator", "")]
public sealed class EndpointFilterInvocationContext<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> : EndpointFilterInvocationContext
{
    public EndpointFilterInvocationContext(HttpContext httpContext, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9)
    {
        HttpContext = httpContext;
        Arg0 = arg0;
        Arg1 = arg1;
        Arg2 = arg2;
        Arg3 = arg3;
        Arg4 = arg4;
        Arg5 = arg5;
        Arg6 = arg6;
        Arg7 = arg7;
        Arg8 = arg8;
        Arg9 = arg9;
    }

    public object? this[int index]
    {
        get => index switch
        {
            0 => Arg0,
            1 => Arg1,
            2 => Arg2,
            3 => Arg3,
            4 => Arg4,
            5 => Arg5,
            6 => Arg6,
            7 => Arg7,
            8 => Arg8,
            9 => Arg9,
            _ => new IndexOutOfRangeException()
        };
        set
        {
            switch (index)
            {
               case 0:
                    Arg0 = (T0)(object?)value!;
                    break;
               case 1:
                    Arg1 = (T1)(object?)value!;
                    break;
               case 2:
                    Arg2 = (T2)(object?)value!;
                    break;
               case 3:
                    Arg3 = (T3)(object?)value!;
                    break;
               case 4:
                    Arg4 = (T4)(object?)value!;
                    break;
               case 5:
                    Arg5 = (T5)(object?)value!;
                    break;
               case 6:
                    Arg6 = (T6)(object?)value!;
                    break;
               case 7:
                    Arg7 = (T7)(object?)value!;
                    break;
               case 8:
                    Arg8 = (T8)(object?)value!;
                    break;
               case 9:
                    Arg9 = (T9)(object?)value!;
                    break;
                default:
                    break;
            }
        }
    }

    /// <inheritdoc />
    public override HttpContext HttpContext { get; }

    /// <inheritdoc />
    public override IList<object?> Arguments => new List<object?>() { Arg0, Arg1, Arg2, Arg3, Arg4, Arg5, Arg6, Arg7, Arg8, Arg9, };

    internal T0 Arg0 { get; set; }
    internal T1 Arg1 { get; set; }
    internal T2 Arg2 { get; set; }
    internal T3 Arg3 { get; set; }
    internal T4 Arg4 { get; set; }
    internal T5 Arg5 { get; set; }
    internal T6 Arg6 { get; set; }
    internal T7 Arg7 { get; set; }
    internal T8 Arg8 { get; set; }
    internal T9 Arg9 { get; set; }
    
    /// <inheritdoc />
    public override T GetArgument<T>(int index)
    {
        return index switch
        {
           0 => (T)(object)Arg0!,
           1 => (T)(object)Arg1!,
           2 => (T)(object)Arg2!,
           3 => (T)(object)Arg3!,
           4 => (T)(object)Arg4!,
           5 => (T)(object)Arg5!,
           6 => (T)(object)Arg6!,
           7 => (T)(object)Arg7!,
           8 => (T)(object)Arg8!,
           9 => (T)(object)Arg9!,
           _ => throw new IndexOutOfRangeException()
        };
    }
}
